version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - '5432:5432'
